// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbv0gZ5LqLj35tNIJ1uc8CKhJvvZu_5tU',
    appId: '1:183851412991:web:f50b3095aa4bb5c648cbca',
    messagingSenderId: '183851412991',
    projectId: 'shayanbhai0308',
    authDomain: 'shayanbhai0308.firebaseapp.com',
    storageBucket: 'shayanbhai0308.appspot.com',
    measurementId: 'G-FDBBW3YKFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-F_KTsvq_7S-eMPY0FFkbXSc5UDxRfuA',
    appId: '1:183851412991:android:367fde5df1ed96da48cbca',
    messagingSenderId: '183851412991',
    projectId: 'shayanbhai0308',
    storageBucket: 'shayanbhai0308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe0PdRNfBcE8ddgDTg58ISaCe9XTZCXfg',
    appId: '1:183851412991:ios:9f8c0a5b3d6b60f348cbca',
    messagingSenderId: '183851412991',
    projectId: 'shayanbhai0308',
    storageBucket: 'shayanbhai0308.appspot.com',
    iosClientId: '183851412991-kij934i2prsdc7hb6k2ve5dfc2dajgc5.apps.googleusercontent.com',
    iosBundleId: 'com.kratos.whatsapp',
  );
}
